### ISSUE TITLE
Неправильная обработка временного периода

### ISSUE THREAD

**Issue by IvLaptev** [RTUITLab/ITLab-DocsGen#19]
Вне зависимости от дат, указанных в запросе, приходит один и тот же файл.

Например, запросы на:
`https://manage.rtuitlab.dev/api/docsgen/downloadxls?begin=2020-05-04&end=2021-01-16`
и
`https://manage.rtuitlab.dev/api/docsgen/downloadxls?begin=2020-01-01&end=2021-01-01`
вернут одинаковый файл от 2018 до 2020 года.

**Comment by CAPCHIK** [comment]
@ginfinn  это к тебе
